name: drag2_matlab
channels:
  - defaults
dependencies:
  - numpy
  - seaborn
  - scipy
  - pandas
  - jupyter
  - python=3.8
  - pyyaml
  - h5py
  - imageio
  - scikit-learn
  - pingouin
  - fastcluster
  - cairo
  - networkx
  - pyxdameraulevenshtein
  - numba
#prefix: /home/lucast4/miniconda3/envs/drag2_matlab
